(()=>{
'use strict';
const BANK={
 history:{
  1:[['Which treaty is generally regarded as ending the Thirty Years’ War in 1648?',['Treaty of Utrecht','Peace of Westphalia','Treaty of Tordesillas','Treaty of Augsburg'],1],['Which ancient Athenian statesman is closely associated with the reforms that preceded classical democracy?',['Pericles','Cleisthenes','Solon','Alcibiades'],1],['The Rosetta Stone contains inscriptions in Greek, Demotic and which form of Egyptian writing?',['Coptic','Hieroglyphs','Linear B','Phoenician'],1],['Which empire used the devshirme system to recruit boys for state service?',['Ottoman Empire','Mughal Empire','Safavid Empire','Byzantine Empire'],0]],
  2:[['Which 1494 agreement divided newly claimed overseas territories between Castile and Portugal?',['Treaty of Tordesillas','Treaty of Zaragoza','Treaty of Alcáçovas','Peace of Cateau-Cambrésis'],0],['The Battle of Hastings in 1066 led to the conquest of England by which ruler?',['Harold Godwinson','William of Normandy','Cnut the Great','Edward the Confessor'],1],['Which Chinese dynasty sponsored the voyages of Zheng He?',['Tang','Song','Ming','Qing'],2],['The Meiji Restoration formally began in which year?',['1853','1868','1877','1890'],1]],
  3:[['Which 1919 treaty imposed major territorial and military terms on Germany after World War I?',['Treaty of Brest-Litovsk','Treaty of Versailles','Treaty of Lausanne','Treaty of Saint-Germain'],1],['Who wrote the 19th-century work The Communist Manifesto with Friedrich Engels?',['Vladimir Lenin','Karl Marx','Mikhail Bakunin','Eduard Bernstein'],1],['Which Byzantine emperor is associated with the codification known as the Corpus Juris Civilis?',['Justinian I','Constantine XI','Heraclius','Basil II'],0],['The Taiping Rebellion occurred primarily during which Chinese dynasty?',['Han','Ming','Qing','Yuan'],2]],
  4:[['Which diplomatic settlement in 1815 reshaped Europe after Napoleon’s defeat?',['Congress of Vienna','Congress of Berlin','Treaty of Paris 1783','Peace of Amiens'],0],['Which pre-Columbian civilization developed the quipu system for recording information?',['Aztec','Maya','Inca','Olmec'],2],['The English Bill of Rights was enacted in which year?',['1649','1689','1714','1776'],1],['Which Abbasid-era center became famous for scholarship and translation in Baghdad?',['House of Wisdom','Al-Azhar','Library of Pergamum','Academy of Gundishapur'],0]]
 },
 science:{
  1:[['What is the primary function of ribosomes?',['DNA replication','Protein synthesis','Lipid storage','Cell movement'],1],['Which particle determines the atomic number of an element?',['Neutron','Electron','Proton','Photon'],2],['What is the SI unit of electric resistance?',['Volt','Ohm','Tesla','Watt'],1],['Which blood cells are primarily responsible for antibody production?',['Red blood cells','Platelets','B lymphocytes','Neutrophils'],2]],
  2:[['Which enzyme unwinds the DNA double helix during replication?',['Ligase','Helicase','Polymerase','Primase'],1],['In an exothermic reaction, heat is generally what?',['Absorbed by surroundings','Released to surroundings','Converted only to light','Destroyed'],1],['Which electromagnetic band has shorter wavelengths than visible violet light?',['Infrared','Microwave','Ultraviolet','Radio'],2],['What is the main gas responsible for most of Earth’s natural greenhouse effect?',['Nitrogen','Water vapor','Oxygen','Argon'],1]],
  3:[['In CRISPR-Cas9 gene editing, Cas9 primarily functions as what?',['RNA transporter','DNA-cutting nuclease','Protein-folding enzyme','Membrane receptor'],1],['What does the second law of thermodynamics imply for an isolated system?',['Entropy tends to decrease','Entropy tends to increase or remain constant','Energy disappears','Temperature must reach zero'],1],['Which quantum number describes the orientation of an electron orbital?',['Principal n','Azimuthal l','Magnetic m_l','Spin m_s'],2],['A Type Ia supernova is strongly associated with the thermonuclear destruction of what?',['A white dwarf','A neutron star','A red giant core','A black hole'],0]],
  4:[['Which observation is a major line of evidence for the expansion of the universe?',['Stellar parallax','Cosmological redshift of distant galaxies','Solar eclipses','Earth’s seasons'],1],['What phenomenon allows a superconductor to expel magnetic field lines?',['Photoelectric effect','Meissner effect','Compton effect','Zeeman effect'],1],['In population genetics, Hardy–Weinberg equilibrium assumes which condition?',['Strong natural selection','Random mating and no evolutionary forces','Constant mutation','Small isolated population'],1],['Which fundamental interaction is mediated by gluons?',['Electromagnetic','Weak','Strong','Gravitational'],2]]
 },
 technology:{
  1:[['Which protocol translates domain names such as example.com into IP addresses?',['HTTP','DNS','FTP','SSH'],1],['What does RAM primarily provide to a computer?',['Permanent storage','Volatile working memory','Power conversion','Network routing'],1],['Which data structure follows FIFO ordering?',['Stack','Queue','Tree','Heap'],1],['What is a hash function commonly used for in computing?',['Mapping data to a fixed-size digest','Increasing monitor resolution','Compressing electricity','Generating physical storage'],0]],
  2:[['What is the main purpose of a public-key cryptosystem?',['Use the same secret key for everyone','Use mathematically related public and private keys','Remove authentication','Eliminate encryption'],1],['Which HTTP status code indicates that a resource was not found?',['200','301','404','500'],2],['What does containerization primarily isolate?',['Only monitor pixels','Application and its dependencies from the host environment','Internet cables','CPU transistors'],1],['Which database model organizes information primarily into tables and relationships?',['Relational','Hierarchical only','Graphical UI','Filesystem'],0]],
  3:[['What problem does the CAP theorem describe in distributed systems?',['CPU cache size','Trade-offs among consistency, availability and partition tolerance','Image compression','Password entropy'],1],['What is a Merkle tree mainly useful for?',['Verifying data integrity efficiently','Rendering 3D scenes','Increasing RAM','Cooling processors'],0],['In asymmetric cryptography, what should normally remain secret?',['Public key','Certificate name','Private key','Algorithm name'],2],['Which technique reduces model inference cost by representing neural-network weights with fewer bits?',['Quantization','Tokenization only','Sharding only','Rasterization'],0]],
  4:[['What does Byzantine fault tolerance aim to handle?',['Only slow hard drives','Arbitrary or malicious failures in distributed participants','Low screen brightness','Database indexing'],1],['In TLS, what does certificate validation primarily help establish?',['The server’s authenticated identity','The monitor’s refresh rate','The CPU temperature','The browser’s font'],0],['Which consensus family is used by Bitcoin’s original protocol?',['Proof of Work','Proof of Authority','Proof of Space only','Raft'],0],['What is a side-channel attack exploiting?',['Only source-code comments','Information leaked by implementation behavior such as timing or power use','A larger database','A faster network cable'],1]]
 },
 geography:{
  1:[['Which strait separates Asia from North America?',['Strait of Gibraltar','Bering Strait','Bosporus','Dardanelles'],1],['Which river flows through Baghdad?',['Tigris','Danube','Nile','Volga'],0],['Which country has the largest land area in the world?',['Canada','China','Russia','Brazil'],2],['Which mountain is the highest above sea level?',['K2','Mount Everest','Kangchenjunga','Lhotse'],1]],
  2:[['Which country contains the world’s largest hot desert, the Sahara?',['Australia','Egypt and several other North African states','Mongolia only','Mexico only'],1],['The Drake Passage separates South America from which continent?',['Africa','Asia','Antarctica','Australia'],2],['Which lake is the deepest freshwater lake by maximum depth?',['Lake Victoria','Lake Baikal','Lake Superior','Lake Tanganyika'],1],['Which ocean current helps moderate western Europe’s climate?',['Gulf Stream/North Atlantic Drift','Peru Current','Benguela Current','Labrador Current'],0]],
  3:[['Which two countries share the world’s longest international land border?',['India and China','Russia and Kazakhstan','USA and Canada','Brazil and Bolivia'],2],['The Danakil Depression is primarily located in which region?',['Horn of Africa','Scandinavia','Patagonia','Central Asia'],0],['Which river has the largest discharge volume of any river?',['Amazon','Nile','Yangtze','Mississippi'],0],['Which tectonic setting created much of the Andes?',['Oceanic-continental subduction','Mid-ocean ridge only','Transform boundary only','Continental rifting only'],0]],
  4:[['Which country is entirely surrounded by South Africa?',['Lesotho','Eswatini','Botswana','Namibia'],0],['The Pamir Mountains are often described as a major mountain crossroads in which part of Asia?',['Central Asia','Southeast Asia','East Asia','South Asia only'],0],['Which drainage basin is the largest in the world by area?',['Congo Basin','Amazon Basin','Ganges Basin','Nile Basin'],1],['The Afar Triple Junction involves the separation of the African Plate, Arabian Plate and which major African plate?',['Somali Plate','Nazca Plate','Scotia Plate','Caribbean Plate'],0]]
 },
 culture:{
  1:[['Which Japanese theatre form is known for elaborate makeup and stylized movement?',['Kabuki','Noh only','Kathakali','Wayang'],0],['A sonnet traditionally contains how many lines in its common English form?',['10','12','14','16'],2],['Which architectural order is characterized by capitals with volutes?',['Doric','Ionic','Corinthian','Tuscan'],1],['Which film movement is strongly associated with postwar Italy and location shooting?',['Italian Neorealism','French New Wave','German Expressionism','Dogme 95'],0]],
  2:[['Which Japanese aesthetic term emphasizes impermanence and imperfection?',['Wabi-sabi','Ikigai','Bushido','Kintsugi'],0],['What is chiaroscuro primarily concerned with in visual art?',['Strong contrasts of light and dark','Perspective from maps','Sound layering','Text typography'],0],['Which literary epic is traditionally attributed to Homer?',['Beowulf','The Odyssey','The Divine Comedy','The Aeneid'],1],['Which Indian classical dance form is traditionally associated with Kerala?',['Kathakali','Bharatanatyam','Odissi','Kathak'],0]],
  3:[['Which movement challenged traditional narrative and visual conventions in European art in the early 20th century?',['Dada','Rococo','Neoclassicism','Academicism'],0],['Kintsugi is the Japanese practice of repairing broken pottery with what symbolic material?',['Gold or precious metal lacquer','Paper pulp','Wax only','Iron nails'],0],['Which Sanskrit dramatic tradition is recognized by UNESCO as an intangible heritage practice from Kerala?',['Kutiyattam','Yakshagana','Lavani','Bihu'],0],['In music, counterpoint primarily involves what?',['Independent melodic lines sounding together','Only percussion','One sustained note','Silence between movements'],0]],
  4:[['Which concept in anthropology describes a culture’s tendency to judge other cultures by its own standards?',['Ethnocentrism','Diffusionism','Syncretism','Liminality'],0],['Which literary technique presents a character’s internal thoughts in a way that can blur narration and consciousness?',['Stream of consciousness','Allegory','Foreshadowing','Epistolary framing'],0],['Which art-historical term refers to the dramatic use of light and dark associated strongly with Baroque painting?',['Tenebrism','Pointillism','Fauvism','Divisionism'],0],['Which UNESCO-listed Indian tradition is a form of Sanskrit theatre from Kerala?',['Kutiyattam','Ramlila','Chhau','Garba'],0]]
 },
 india:{
  1:[['Which ancient site in Gujarat is recognized by UNESCO as a Harappan city?',['Dholavira','Sanchi','Hampi','Nalanda'],0],['The Ajanta Caves are especially famous for which historical artistic tradition?',['Buddhist paintings and rock-cut architecture','Roman mosaics','Viking runes','Mughal miniature only'],0],['Which city is associated with the Jantar Mantar astronomical observatory complex inscribed by UNESCO?',['Jaipur','Surat','Patna','Mysuru'],0],['Which Indian classical language is central to the literary tradition of the Sangam corpus?',['Tamil','Persian','Pali','Prakrit only'],0]],
  2:[['Which dynasty is associated with the Brihadisvara Temple at Thanjavur?',['Chola','Maurya','Kushan','Pala'],0],['The Battle of Plassey took place in which year?',['1757','1764','1772','1857'],0],['Which movement began with Gandhi’s Salt March in 1930?',['Civil Disobedience Movement','Quit India Movement','Swadeshi Movement','Home Rule Movement'],0],['Which rock shelters in Madhya Pradesh are famous for prehistoric paintings and are UNESCO-listed?',['Bhimbetka','Elephanta','Badami','Udayagiri'],0]],
  3:[['Which Mughal emperor commissioned the Taj Mahal as a mausoleum for Mumtaz Mahal?',['Akbar','Jahangir','Shah Jahan','Aurangzeb'],2],['Which 1950 document established India as a sovereign democratic republic with a written constitutional framework?',['Constitution of India','Government of India Act 1935','Indian Councils Act','Charter Act'],0],['Which ancient university site in Bihar is UNESCO-listed as Nalanda Mahavihara?',['Nalanda','Taxila','Vikramashila','Valabhi'],0],['Which 2025 UNESCO inscription recognizes a network of forts and military landscapes associated with the Maratha polity?',['Maratha Military Landscapes of India','Hill Forts of Rajasthan','Great Living Chola Temples','Historic City of Ahmedabad'],0]],
  4:[['Which inscription is a major source for the early history of Emperor Ashoka’s reign and his dhamma policy?',['Major Rock Edicts','Allahabad Pillar only','Aihole Inscription','Junagadh Inscription only'],0],['The permanent settlement of 1793 is most closely associated with which British governor-general?',['Lord Cornwallis','Lord Wellesley','Lord Dalhousie','Lord Curzon'],0],['Which constitutional body conducts elections to Parliament and state legislatures in India?',['Election Commission of India','Finance Commission','UPSC','CAG'],0],['Which UNESCO site is the world’s only mixed natural-and-cultural World Heritage property in India in the cited listing?',['Khangchendzonga National Park','Kaziranga','Western Ghats','Sundarbans'],0]]
 },
 media:{
  1:[['A source that publishes a correction to a factual error is demonstrating which useful media practice?',['Accountability','Virality','Clickbait','Anonymity'],0],['What is reverse-image searching mainly useful for?',['Finding earlier or related appearances of an image','Increasing image resolution','Removing metadata automatically','Encrypting a photo'],0],['Which clue should make you cautious about a sensational headline?',['It gives no verifiable source','It uses a clear primary document','It names the methodology','It links to the full study'],0],['What is the difference between a fact and an opinion?',['A fact is testable against evidence; an opinion expresses a judgment','Facts are always popular','Opinions can never be supported','There is no difference'],0]],
  2:[['Why is lateral reading useful when evaluating an unfamiliar website?',['You leave the site to check what other credible sources say about it','You read every sentence twice','You disable the browser','You only inspect the logo'],0],['What is source laundering?',['Presenting information through a seemingly independent source while hiding its original or weak provenance','Encrypting a source','Translating an article','Removing ads'],0],['A study’s abstract claims a causal effect, but the methods only show correlation. What is the main concern?',['The conclusion may overstate what the evidence supports','The font is too small','The sample must be perfect','Correlation always proves causation'],0],['Why should publication date matter when checking a claim?',['Evidence and circumstances can change over time','Older sources are always false','Newer sources are always true','Dates only matter for photographs'],0]],
  3:[['What does cherry-picking evidence mean?',['Selecting supporting evidence while ignoring relevant contradictory evidence','Using multiple independent sources','Checking original documents','Correcting a typo'],0],['Which source is generally strongest for verifying what a government agency officially announced?',['The agency’s primary statement or document','An anonymous meme','A random comment','A repost without attribution'],0],['Why can an authentic image still mislead?',['Its context, date or location may be misrepresented','Authentic images contain no facts','Cameras invent pixels','Metadata is always perfect'],0],['What is motivated reasoning?',['Evaluating evidence in a way influenced by a desired conclusion','Using formal logic only','Avoiding all beliefs','Reading a source alphabetically'],0]],
  4:[['A viral claim cites a real paper, but the paper does not contain the claimed result. What should you conclude?',['The citation does not substantiate the claim','The claim is true because a paper exists','The journal guarantees the claim','The headline is enough'],0],['What is epistemic humility in research and media literacy?',['Recognizing the limits of what the available evidence can establish','Refusing all evidence','Believing every expert equally','Avoiding uncertainty'],0],['Why can a high follower count be weak evidence of credibility?',['Popularity does not independently establish accuracy or expertise','Followers are always bots','Experts cannot have followers','Algorithms verify every claim'],0],['If two independent high-quality sources disagree, what is the best next step?',['Compare their evidence, methods, dates and primary sources before deciding','Choose the one with more likes','Average the claims','Assume both are false'],0]]
 },
 mixed:{
  1:[['Which planet is the largest in the Solar System?',['Earth','Jupiter','Saturn','Neptune'],1],['Who painted the Mona Lisa?',['Michelangelo','Leonardo da Vinci','Raphael','Caravaggio'],1],['Which country is home to Machu Picchu?',['Peru','Chile','Bolivia','Ecuador'],0],['Which element has atomic number 6?',['Oxygen','Carbon','Nitrogen','Boron'],1]],
  2:[['Which treaty created the European Economic Community in 1957?',['Treaty of Rome','Treaty of Lisbon','Treaty of Maastricht','Treaty of Nice'],0],['Which organelle contains most eukaryotic cellular DNA?',['Ribosome','Mitochondrion only','Nucleus','Golgi apparatus'],2],['Which strait connects the Mediterranean Sea with the Atlantic Ocean?',['Gibraltar','Bering','Malacca','Hormuz'],0],['Which Indian site is associated with the Great Living Chola Temples?',['Brihadisvara Temple at Thanjavur','Sanchi Stupa','Taj Mahal','Qutb Minar'],0]],
  3:[['Which astronomical measurement is used to define an astronomical unit?',['Average Earth–Sun distance','Earth’s circumference','Sun’s radius','Moon’s orbital period'],0],['Which empire reached its height under Suleiman I?',['Ottoman','Mali','Gupta','Inca'],0],['Which computer security property is primarily about preventing unauthorized alteration of data?',['Integrity','Availability','Latency','Throughput'],0],['Which Indian heritage site was inscribed by UNESCO in 2025 under Maratha Military Landscapes?',['A network of Maratha military landscapes','Only the Taj Mahal','Only Ajanta Caves','Only Kaziranga'],0]],
  4:[['Which effect explains why distant galaxies’ light is shifted toward longer wavelengths as space expands?',['Cosmological redshift','Doppler-freeze effect','Photoelectric effect','Meissner effect'],0],['Which historical agreement is associated with the post-Napoleonic European balance of power?',['Congress of Vienna settlement','Treaty of Tordesillas','Magna Carta','Edict of Milan'],0],['Which distributed-systems concept states that under a network partition, a system cannot simultaneously guarantee both consistency and availability in the general CAP model?',['CAP theorem','Moore’s law','Amdahl’s law','Metcalfe’s law'],0],['Which media-literacy action best tests whether a viral claim’s cited study really supports it?',['Open the original study and compare the claim with its methods and results','Read only the headline','Check the number of shares','Search for the same claim on social media'],0]]
 }
};
const NAMES={history:'History',science:'Science',technology:'Technology',geography:'Geography',culture:'Culture',india:'India',media:'Media Literacy',mixed:'Mixed'};
const ICONS={history:'🏛️',science:'⚗️',technology:'◈',geography:'◎',culture:'🎭',india:'✦',media:'⌁',mixed:'✧'};
let cat='history',level=1,idx=0,score=0,answered=false;
const qEl=()=>document.getElementById('question'),optEl=()=>document.getElementById('options'),fbEl=()=>document.getElementById('feedback');
function questions(){return BANK[cat][level]||[]}
function renderLevels(){
 const categories=document.querySelector('.categories'); if(!categories)return;
 categories.innerHTML=Object.keys(NAMES).map(k=>`<button class="category ${k===cat?'active':''}" data-cat="${k}"><div class="icon">${ICONS[k]}</div><b>${NAMES[k]}</b><small>4 hard levels · 4 fresh questions each</small></button>`).join('');
 let ls=document.getElementById('levelSelector'); if(!ls){ls=document.createElement('section');ls.id='levelSelector';categories.before(ls)}
 ls.innerHTML=`<div class="level-head"><span>Choose difficulty</span><small>${NAMES[cat]} · ${questions().length} questions per level</small></div><div class="levels">${[1,2,3,4].map(n=>`<button class="level ${n===level?'active':''}" data-level="${n}"><span>${['I','II','III','IV'][n-1]}</span><b>Level ${n}</b><small>${['Advanced','Hard','Expert','Master'][n-1]}</small></button>`).join('')}</div>`;
 categories.querySelectorAll('.category').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;level=1;renderLevels();start()});
 ls.querySelectorAll('.level').forEach(b=>b.onclick=()=>{level=+b.dataset.level;renderLevels();start()});
}
function start(){idx=0;score=0;answered=false;document.getElementById('questionArea').classList.remove('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('categoryLabel').textContent=`${NAMES[cat]} · Level ${level}`;renderQuestion()}
function renderQuestion(){
 const qs=questions(),item=qs[idx];answered=false;
 document.getElementById('counter').textContent=`Question ${idx+1} / ${qs.length}`;document.getElementById('progress').style.width=((idx)/qs.length*100)+'%';document.getElementById('scoreText').textContent=`Score: ${score}`;qEl().textContent=item[0];fbEl().textContent='';optEl().innerHTML=item[1].map((x,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('');optEl().querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.i));document.getElementById('next').disabled=true;document.getElementById('next').textContent=idx===qs.length-1?'Finish →':'Next question →';
}
function answer(choice){if(answered)return;answered=true;const item=questions()[idx],buttons=[...optEl().querySelectorAll('.option')];buttons.forEach(b=>b.disabled=true);buttons[item[2]].classList.add('correct');if(choice===item[2]){score++;fbEl().textContent='Correct — strong work.'}else{buttons[choice].classList.add('wrong');fbEl().textContent=`Not quite. Correct answer: ${item[1][item[2]]}.`}document.getElementById('scoreText').textContent=`Score: ${score}`;document.getElementById('next').disabled=false}
function next(){if(!answered)return;if(idx<questions().length-1){idx++;renderQuestion()}else finish()}
function finish(){document.getElementById('questionArea').classList.add('hidden');document.getElementById('result').classList.remove('hidden');document.getElementById('progress').style.width='100%';document.getElementById('finalScore').textContent=`${score}/${questions().length}`;const perfect=score===questions().length;document.getElementById('trophy').textContent=perfect?'🏆':'✦';document.getElementById('resultTitle').textContent=perfect?'Perfect run.':'Practice complete.';document.getElementById('resultText').textContent=perfect?`Outstanding — you cleared ${NAMES[cat]} Level ${level} with every answer correct. Ready for the next challenge?`:`You scored ${score} out of ${questions().length} on ${NAMES[cat]} Level ${level}. Try the level again or move up when you’re ready.`;if(perfect)celebrate()}
function celebrate(){const c=document.getElementById('celebrate');c.innerHTML='';for(let i=0;i<90;i++){const s=document.createElement('i');s.className='confetti';s.style.left=Math.random()*100+'%';s.style.setProperty('--x',(Math.random()*260-130)+'px');s.style.animationDelay=Math.random()*.35+'s';s.style.background=['#ff4928','#ff8b45','#f5f2ee','#65d39d'][i%4];c.appendChild(s)}const spark=document.createElement('div');spark.className='spark';spark.textContent='🎉';c.appendChild(spark);setTimeout(()=>c.innerHTML='',2300)}
function init(){
 if(!document.querySelector('.categories')||!document.getElementById('next'))return;
 const style=document.createElement('style');style.textContent=`#levelSelector{margin:-8px 0 24px}.level-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:10px;color:#c9c2bd;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:1.5px}.level-head small{color:#6f6864;font-size:9px;text-transform:none;letter-spacing:0;font-weight:500}.levels{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.level{border:1px solid #2a2224;background:linear-gradient(145deg,rgba(255,255,255,.04),rgba(255,67,28,.018));color:#ddd;border-radius:16px;padding:13px;text-align:left;cursor:pointer;transition:.2s}.level span{display:inline-grid;place-items:center;width:28px;height:28px;border-radius:9px;background:rgba(255,75,35,.08);color:#ff8b45;font-size:10px;font-weight:900;margin-bottom:8px}.level b,.level small{display:block}.level b{font-size:11px}.level small{margin-top:4px;color:#716a66;font-size:9px}.level:hover,.level.active{transform:translateY(-2px);border-color:rgba(255,94,55,.7);box-shadow:0 15px 40px rgba(0,0,0,.3),0 0 25px rgba(255,66,30,.08)}@media(max-width:650px){.levels{grid-template-columns:repeat(2,1fr)}.level-head{align-items:start;gap:8px;flex-direction:column}}`;document.head.appendChild(style);
 document.getElementById('next').onclick=next;document.getElementById('restart').onclick=start;renderLevels();start();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
